### ISSUE TITLE
Cannot use extracted SpanContext as parent

### ISSUE THREAD

**Issue by maxwindiff** [openzipkin-contrib/brave-opentracing#4]
Running this:

``` java
    @Test
    public void testExtractAsParent() throws Exception {
        Map<String,String> map = new HashMap<String,String>() {{
            put(BraveHttpHeaders.Sampled.getName(), "1");
            put(BraveHttpHeaders.TraceId.getName(), "123");
            put(BraveHttpHeaders.SpanId.getName(), "234");
        }};
        TextMapExtractAdapter adapter = new TextMapExtractAdapter(map);
        BraveTracer tracer = new BraveTracer();
        SpanContext parent = tracer.extract(Format.Builtin.TEXT_MAP, adapter);
        Span child = tracer.buildSpan("child").asChildOf(parent).start(); // line 333
    }
```

Causes this error:

```
java.lang.ClassCastException: io.opentracing.BraveSpanBuilder cannot be cast to io.opentracing.BraveSpan

    at io.opentracing.BraveSpanBuilder.getParent(BraveSpanBuilder.java:94)
    at io.opentracing.BraveSpanBuilder.createSpan(BraveSpanBuilder.java:43)
    at io.opentracing.BraveSpanBuilder.createSpan(BraveSpanBuilder.java:24)
    at io.opentracing.AbstractSpanBuilder.start(AbstractSpanBuilder.java:102)
    at io.opentracing.BraveTracerTest.testExtractAsParent(BraveTracerTest.java:333)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by michaelsembwever** [comment]
taking a look…

**Comment by michaelsembwever** [comment]
See https://github.com/openzipkin/brave-opentracing/pull/5
